---
title: "Data"
bibliography: bib.bib
---

Unless otherwise noted, all data are from @rosner2015fundamentals, downloaded from the book's [companion site](https://www.cengage.com/cgi-wadsworth/course_products_wp.pl?fid=M20b&product_isbn_issn=9781305268920).

I did some cleaning (changing `9`'s to `NA`'s, recoding numerics to informative characters, etc).

# betacar

High doses of beta-carotene in food have been linked to a reduced cancer risk in some observational studies. A study considered four beta-carotene capsule preparations: Solatene (30 mg), Roche (60 mg), and two from BASF (30 mg and 60 mg). To test their effectiveness in raising plasma-carotene levels, 23 volunteers were randomized to one of the four preparations, taking one pill every other day for 12 weeks. The primary endpoint was the plasma carotene level after prolonged ingestion.

- [betacar.csv](./data/betacar.csv)
  - `Prepar`: Preparation.
    - Possible values: `SOL`, `ROCHE`, `BASF-30`, `BASF-60`.
  - `Id`: Subject #
  - `Base1lvl`: 1st Baseline Level
  - `Base2lvl`: 2nd Baseline Level
  - `Wk6lvl`: Week 6 Level
  - `Wk8lvl`: Week 8 Level
  - `Wk10lvl`: Week 10 Level
  - `Wk12lvl`: Week 12 Level

# birthweight

The birthweights of 1000 consecutive infants born at Boston City Hospital, which serves a low-income population.

- [birthweight.csv](./data/birthweight.csv)
  - `id`: ID
  - `weight`: Birthweight (oz)

# blood

Data from a case-control study investigated various plasma risk factors for breast cancer. The women were matched approximately by age at the time of blood draw, fasting status, and, when possible, current postmenopausal hormone (PMH) use at the time of blood draw. Each matched set included one case and either one or two controls, although some sets are incomplete due to missing data. The matching variable is `matchid`.

- [blood.csv](./data/blood.csv)
  - `Id`: ID
  - `matchid`: Matched ID
  - `case`: Case/control.
    - Possible values: `case`, `control`.
  - `curpmh`: Current PMH use.
    - Possible values: `yes`, `no`.
  - `ageblood`: Age at blood draw
  - `estradol`: Estradiol
  - `estrone`: Estrone
  - `testost`: Testosterone
  - `prolactn`: Prolactin

# boneden

A study in Australia examined the relationship between bone density and cigarette smoking in middle-aged female twins with different smoking histories. Forty-one pairs of twins visited a hospital in Victoria, Australia, where their bone density was measured. Participants also completed questionnaires providing information on their tobacco use, alcohol, coffee, and tea consumption, calcium intake from dairy products, menopausal and reproductive history, fracture history, use of oral contraceptives or estrogen replacement therapy, and physical activity levels. Tobacco consumption was measured in pack-years, with one pack-year defined as smoking one pack of cigarettes per day for one year.

- [boneden.csv](./data/boneden.csv)
  - `ID`: ID
  - `Age`:  Age (yrs)
  - `zyg`: Twin type.
    - Possible values: `mz`, `dz`
  - Twin 1  Lighter Smoking Twin
    - `ht1`: Height (cm)
    - `wt1`: Weight (kg)
    - `tea1`: Tea  (cups/week)
    - `cof1`: Coffee  (cups/week)
    - `alc1`: Alcohol  (drinks/week)
    - `cur1`: Current Smoking (cigarettes/day)
    - `men1`: Menopause Status.
      - Possible values: `pre`, `post`, `unknown`
    - `pyr1`: Pack-years smoking
    - `ls1`: Lumbar spine (g/cm$^2$)
    - `fn1`: Femoral neck (g/cm$^2$)
    - `fs1`: Femoral shaft (g/cm$^2$)
  - Twin 2  Heavier Smoking Twin
    - `ht2`: Height (cm)
    - `wt2`: Weight (kg)
    - `tea2`: Tea  (cups/week)
    - `cof2`: Coffee  (cups/week)
    - `alc2`: Alcohol  (drinks/week)
    - `cur2`: Current Smoking (cigarettes/day)
    - `men2`: Menopause Status.
      - Possible values: `pre`, `post`, `unknown`
    - `pyr2`: Pack-years smoking
    - `ls2`: Lumbar spine (g/cm$^2$)
    - `fn2`: Femoral neck (g/cm$^2$)
    - `fs2`: Femoral shaft (g/cm$^2$)

# botox

A study on patients with piriformis syndrome compared the effects of three types of injections: triamcinolone with lidocaine (`TL`), a placebo (`Placebo`), and Botox (`Botox`). The patients were randomly assigned to these groups in a 3:1:2 ratio and received injections directly into the piriformis muscle. They were evaluated at 2 weeks, 1 month, and monthly up to 17 months, though many missed visits. Improvement in pain was measured on a scale from 0% to 100% (higher means more improved). The study involved 69 patients, with one having the condition in both legs. The goal was to compare the efficacy between the groups, considering age, gender, and affected side as potential influencing factors.

- [botox.csv](./data/botox.csv)
  - `ID`: ID
  - `group`:
    - Possible values: `TL`, `Placebo`, `Botox`
  - `side`: left (`L`), middle (`M`), or right (`R`).
  - `gender`: `male` or `female`
  - `age`: in years
  - `pain0`: pain score month 0
  - `pain05`: pain score month 0.5
  - `pain1`: pain score month 1
  - `pain2`: pain score month 2
  - `pain3`: pain score month 3
  - `pain4`: pain score month 4
  - `pain5`: pain score month 5
  - `pain6`: pain score month 6
  - `pain7`: pain score month 7
  - `pain8`: pain score month 8
  - `pain9`: pain score month 9
  - `pain10`: pain score month 10
  - `pain11`: pain score month 11
  - `pain12`: pain score month 12
  - `pain13`: pain score month 13
  - `pain14`: pain score month 14
  - `pain15`: pain score month 15
  - `pain16`: pain score month 16
  - `pain17`: pain score month 17

# breast

The data set includes 1200 postmenopausal women from the NHS, free of cancer in 1990. Of these, 200 were using postmenopausal hormones (PMH) in 1990, and 1000 had never used them. The study aimed to link PMH use in 1990 to breast cancer incidence from 1990 to 2000. Fifty-three women developed breast cancer during this period. PMH use was categorized by current use and duration of use in 1990, with separate durations for estrogen and estrogen plus progesterone. Each woman has a return date for the 1990 questionnaire and a follow-up date, which is either the date of breast cancer diagnosis or the date of the last questionnaire by 2000. The file also includes data on other breast cancer risk factors as of 1990.

- [breast.csv](./data/breast.csv)
  - `Id`: ID
  - `case`: Treatment
    - Possible values: `case`,`control`
  - `age`: age
  - `agemenar`: age at menarche
  - `agemenop`: age at menopause
  - `afb`: age at first birth  98=nullip
  - `parity`: parity
  - `bbd`: Benign Breast disease.
    - Possible values: `yes`, `no`
  - `famhx`: family history breast cancer.
    - Possible values: `yes`, `no`
  - `bmi`: BMI (kg/m**2)
  - `hgt`: Height (inches)
  - `alcohol`: Alcohol use (grams/day)
  - `pmh`: PMH status.
    - Possible values: `never user`, `current user`
  - `dur3`: Duration of Estrogen use  (months)
  - `dur4`: Duration of Estrogen + progesterone use  (months)
  - `csmk`: Current Smoker.
    - Possible values: `yes`, `no`
  - `psmk`: Past smoker.
    - Possible values: `yes`, `no`
  - `foluptm`: Months of follow up. Note: Some subjects provided no follow up after the 1990 questionnaire and `foluptm` = 0 for these people

# cholesterol

Cholesterol levels from 24 hospital employees who switched from a standard American diet to a vegetarian diet for one month. Their serum cholesterol was measured before and after the diet change.

- [cholesterol.csv](./data/cholesterol.csv)
  - `Subject`: ID
  - `Before`: Serum-cholesterol levels before diet change (mg/dL)
  - `After`: Serum-cholesterol levels after diet change (mg/dL)
  - `Difference`: Difference in serum-cholesterol levels, `Before - After`, where positive numbers indicate a reduction in serum-cholesterol levels.

# corneal

Fluoroquinolones, antibiotics for bacterial infections, are FDA-approved for systemic use. However, post-approval studies indicate a risk of peripheral neuropathy, leading to updated safety labeling.

A small clinical trial tested the safety and effectiveness of two fluoroquinolone eye drops (drugs `M` and `G`) and a placebo (drug `P`) for bacterial eye infections. Ninety-three subjects were randomly assigned to three groups, each receiving one active drug and a placebo in opposite eyes. Participants used the drops four times daily for 10 days. The primary outcome was corneal sensitivity, measured in millimeters, with higher values indicating more normal sensitivity.

Corneal sensitivity was assessed at baseline, 7 days, and 14 days, with measurements taken from the central cornea and four quadrants (superior, inferior, temporal, nasal).

- [corneal.csv](./data/corneal.csv)
  - `id`: ID
  - `tr`: Treatment.
    - Possible values: `M`, `G`, `P`
  - `c1`: Central  visit 1
  - `s1`: Superior visit 1
  - `i1`: Inferior Visit 1
  - `t1`: Temporal visit 1
  - `n1`: Nasal Visit 1
  - `c2`: Central Visit 2(day 7)
  - `s2`: Superior Visit 2
  - `i2`: Inferior Visit 2
  - `t2`: Temporal Visit 2
  - `n2`: Nasal Visit 2
  - `c3`: Central Visit 3(day 14)
  - `s3`: Superior Visit 3
  - `i3`: Inferior Visit 3
  - `t3`: Temporal Visit 3
  - `n3`: Nasal Visit 3

# diabetes

Type I diabetes is common in children and requires regular insulin shots to prevent long-term complications like neurologic, vision, kidney issues, heart disease, and premature death.

The impact of diabetes control on childhood growth is less clear. To study this, adolescent boys aged 9−15 were examined about every 3 months. Each exam measured diabetes control using glycosylated hemoglobin (HgbA1c), where higher HgbA1c indicates poorer control (normal <7.0). Age, height, and weight were also recorded. Data includes 94 boys over 910 visits.

The main question is the overall relationship between glycemic control and growth, primarily weight, for the entire group, not individual cases.

- [diabetes.csv](./data/diabetes.csv)
  - `ID`: ID
  - `mon_a1c`: Month A1c
  - `day_a1c`: Day A1c
  - `yr_a1c`: Yr A1c
  - `age_yrs`: Age in years
  - `gly_a1c`: Hemoglobin A1c
  - `ht_cm`: Height in cm
  - `wt_kg`: Weight in kg

# ear

This dataset includes 203 children with acute otitis media (OME) from a randomized clinical trial. Each child had OME in one or both ears and received a 14-day course of either cefaclor (CEF) or amoxicillin (AMO). Middle-ear status was assessed after the 14-day treatment.

- [ear.csv](./data/ear.csv)
  - `Id`: ID
  - `Clear`: Clearance by 14 days,
    - Possible values: `yes`, `no`
  - `Antibo`: Antibiotic.
    - Possible values: `CEF`, `AMO`
  - `Age`: Age.
     Possible values: `<2` yrs, `2-5` yrs, `6+` yrs.
  - `Ear`: Ear,
   - `1` = 1st ear
   - `2` = 2nd ear

# eff, nephro, and oto

Aminoglycoside antibiotics are crucial for treating severe gram-negative bacterial infections in hospitalized patients. Despite their toxicity and the development of new antibiotics, aminoglycosides remain widely used. Choosing the right aminoglycoside depends on the clinical situation, antimicrobial spectrum, cost, and side effects like nephrotoxicity and auditory toxicity. Numerous trials comparing these antibiotics have varied in design and conclusions, often lacking sufficient sample sizes to detect small differences.

To better understand their true effects, a meta-analysis of all randomized trials was conducted. This analysis included 45 trials from 1975 to 1985, comparing amikacin, gentamicin, netilmicin, sisomicin, and tobramycin. Data from 37 trials were suitable for comparison, focusing on efficacy, nephrotoxicity, and auditory toxicity. Efficacy was defined by bacterial or clinical response as reported by each trial, nephrotoxicity by the percentage of kidney-related toxic events reported, and auditory toxicity by the diffence in pre- and post-treatment audiograms. The data is organized into three sets: eff.csv, nephro.csv, and oto.csv, with separate records for each antibiotic and endpoint.

- [eff.csv](./data/eff.csv)
  - `Name`: Study name
  - `Id`: Study Number
  - `Endpnt`: Endpoint, `1` = efficacy
  - `Antibio`: Antibiotic.
    - Possible values: `Amikacin`, `Gentamicin`, `Netilmicin`, `Sisomycin`, `Tobramycin`.
  - `Samp_sz`: Sample Size
  - `Cured`: Number Cured

- [nephro.csv](./data/nephro.csv)
  - `name`: Study name
  - `id`: Study number
  - `Endpnt`: Endpoint  `2` = nephrotoxicity
  - `Antibio`: Antibiotic.
    - Possible values: `Amikacin`, `Gentamicin`, `Netilmicin`, `Sisomycin`, `Tobramycin`
  - `Samp_sz`: Sample size
  - `Side_eff`: Number with side effects

- [oto.csv](./data/oto.csv)
  - `Name`: Study Name
  - `Id`: Study Number
  - `Endpnt`: Endpoint.
    - Possible values: `efficacy`, `nephrotoxicity`, `ototoxicity`.
  - `Antibio`: Antibiotic.
    - Possible values: `Amikacin`, `Gentamicin`, `Netilmicin`, `Sisomycin`, `Tobramycin`.
  - `Samp_sz`: Sample Size
  - `Side_eff`: Number with side effect

# endocrin

The data set contains split-sample plasma measurements of four hormones for each of five subjects, all from one laboratory.

- [endocrin.csv](./data/endocrin.csv)
  - `Subject`: Subject number
  - `Replicat`: Replicate number
  - `Estrone`: Estrone
  - `Estradol`: Estradiol
  - `Androste`: Androstenedione
  - `Testost`: Testosterone

# estradl

Obesity is common in American society and a risk factor for breast cancer in postmenopausal women, possibly due to increased estrogen levels, particularly serum estradiol. Researchers studied 151 African American and 60 Caucasian premenopausal women, measuring adiposity using body mass index (BMI) (a measure of overall adioposity) and waist-hip ratio (WHR) (a measure of abdominal adioposity). They also obtained a complete hormonal profile, including serum estradiol, and assessed other breast cancer risk factors: ethnicity, age, number of children, age at first birth, presence of children, and age at menarche.

- [estradl.csv](./data/estradl.csv)
  - `Id`: Identification number
  - `Estradl`: Estradiol
  - `Ethnic`: Ethnicity.
    - Possible values: `African-American`, `Caucasian`
  - `Entage`: Age
  - `Numchild`: Parity, number of children
  - `Agefbo`: Age at 1st birth (=0 if numchild=0)
  - `Anykids`: any children.
    - Possible values: `yes`, `no`.
  - `Agemenar`: age at menarche
  - `BMI`: Body Mass Index
  - `WHR`: waist-hip ratio

# estrogen

Three distinct two-period crossover studies were conducted with different subject groups, measuring systolic and diastolic blood pressure. In Study 1, 0.625 mg of estrogen was compared with a placebo. Study 2 compared 1.25 mg of estrogen with a placebo. Study 3 compared 1.25 mg of estrogen with 0.625 mg of estrogen. Each active treatment period lasted for four weeks, with a two-week washout period between them.

- [estrogen.csv](./data/estrogen.csv)
  - `Id`: ID
  - `std_typ`: Study type.
    - Possible values: `0.625MG VS PLACEBO`, `1.25MG VS PLACEBO`, `1.25MG VS 0.625MG`
  - `period`: Period
  - `trtgrp`: Treatment.
    - Possible values: `PLACEBO`, `0.625MG`, `1.25MG`
  - `sysd1r1`: Systolic blood pressure day 1 reading 1
  - `diasd1r1`: Diastolic blood pressure day 1 reading 1
  - `sysd1r2`: Systolic blood pressure day 1 reading 2
  - `diasd1r2`: Diastolic blood pressure day 1 reading 2
  - `sysd1r3`: SYSTOLIC BP  DAY 1 reading 3
  - `diasd1r3`: Diastolic blood pressure day 1 reading 3
  - `sysd2r1`: Systolic blood pressure day 2 reading 1
  - `diasd2r1`: Diastolic blood pressure day 2 reading 1
  - `sysd2r2`: Systolic blood pressure day 2 reading 2
  - `diasd2r2`: Diastolic blood pressure day 2 reading 2
  - `sysd2r3`: Systolic blood pressure day 2 reading 3
  - `diasd2r3`: Diastolic blood pressure day 2 reading 3
  - `sysd3r1`: Systolic blood pressure day 3 reading 1
  - `diasd3r1`: Diastolic blood pressure day 3 reading 1
  - `sysd3r2`: Systolic blood pressure day 3 reading 2
  - `diasd3r2`: Diastolic blood pressure day 3 reading 2
  - `sysd3r3`: Systolic blood pressure day 3 reading 3
  - `diasd3r3`: Diastolic blood pressure day 3 reading 3

# fev

Forced expiratory volume (FEV) is a measure of pulmonary function that quantifies the volume of air expelled in one second of sustained effort. This dataset includes FEV measurements from 1980 for 654 children aged 3 to 19 who participated in the Childhood Respiratory Disease (CRD) Study in East Boston, Massachusetts. The data are part of a longitudinal study aimed at tracking changes in pulmonary function over time in children.

- [fev.csv](./data/fev.csv)
  - `Id`: ID number
  - `Age`: Age (yrs)
  - `FEV`: FEV (liters)
  - `Hgt`: Height (inches)
  - `Sex`: Sex.
    - Possible values: `female`, `male`
  - `Smoke`: Smoking Status.
    - Possible values: `non-current`, `current smoker`.

# field

Retinitis pigmentosa (RP) is a hereditary eye disease that can lead to substantial vision loss or blindness. It has dominant, recessive, and sex-linked forms, with mutations in the rhodopsin (RHO) gene linked to dominant cases and RPGR gene mutations linked to sex-linked cases.

The data file field.csv contains visual field data for approximately 100 patients each from the RHO and RPGR groups. Visual field, measured in degrees$^2$, indicates the area of vision. The dataset includes longitudinal data with varying follow-up times from a minimum of 3 years to a maximum of about 25-30 years. Measurements are provided separately for the right eye (OD) and the left eye (OS).

- [field.csv](./data/field.csv)
  - `id`: ID
  - `group`: group.
    - Possible values: `RHO`, `RPGR`
  - `age`: age at visit  (years)
  - `gender`: gender. Note: all RPGR individuals have to be male.
    - Possible values: `male`, `female`.
  - `dtvisit`: date of visit (YYYY-MM-DD)
  - `folowup`: time from 1st visit in years
  - `totfldod`: total field area right eye (OD) in degrees
  - `totfldos`: total field area left eye (OS) in degrees

# heart

- [heart.csv](./data/heart.csv)
  - `Diagnosis`:	Possible values:
    - `Y1` = normal
    - `Y2` = atrial septal defect without pulmonary stenosis or pulmonary hypertension
    - `Y3` = ventricular septal defect with valvular pulmonary stenosis
    - `Y4` = isolated pulmonary hypertension
    - `Y5` = transposed great vessels
    - `Y6` = ventricular septal defect without pulmonary hypertension
    - `Y7` = ventricular septal defect with pulmonary hypertension
  - `Prevalence`: Prevalence
  - `X1`: age 1-20 years old
  - `X2`: age>20 years old
  - `X3`: mild cyanosis
  - `X4`: easy fatigue
  - `X5`: chest pain
  - `X6`: repeated respiratory infections
  - `X7`: EKG axis more than 110

# hormone

An experiment was conducted to study the effects of avian pancreatic polypeptide (aPP), cholecystokinin (CCK), vasoactive intestinal peptide (VIP), and secretin on pancreatic and biliary secretions in laying hens. Researchers aimed to determine how these hormones affect the flow rates and pH values of these secretions.

White Leghorn hens, aged 14-29 weeks, were surgically fitted with cannulas for collecting secretions and a jugular cannula for hormone infusion. Each hen underwent one trial per day, as long as her cannulas remained functional, leading to varying trial numbers per hen.

Each trial started with a 20-minute saline infusion, followed by the collection of pancreatic and biliary secretions. The flow rates and pH values were measured. This was followed by a 40-minute hormone infusion, with measurements repeated afterward.

The data set "hormone.csv" includes data for the four hormones and saline, with each trial recorded as one entry and 11 associated variables.

- [hormone.csv](./data/hormone.csv)
  - `ID`: ID
  - `Bilsecpr`: Biliary secretion-pre
  - `Bilphpr`: Biliary pH-pre
  - `Pansecpr`: Pancreatic secretion-pre
  - `Panphpr`: Pancreatic pH-pre
  - `Dose`: Dose
  - `Bilsecpt`: Biliary secretion-post
  - `Bilphpt`: Biliary pH-post
  - `Pansecpt`: Pancreatic secretion-post
  - `Panphpt`: Pancreatic pH-post
  - `Hormone`: Hormone.
    - Possible values: `SAL`, `APP`, `CCK`, `SEC`, `VIP`.

# hospital

These data are part of a larger data set gathered from individuals discharged from a specific Pennsylvania hospital. It was collected as part of a retrospective chart review focusing on antibiotic usage in hospitals.

- [hospital.csv](./data/hospital.csv)
  - `Id`: id no.
  - `Dur_stay`: Duration of hospital stay
  - `Age`: Age
  - `Sex`: Sex.
    - Possible values: `male`, `female`
  - `Temp`: First temperature following admission
  - `WBC`: First WBC(x1000) following admission
  - `Antibio`: Received antibiotic.
    - Possible values: `yes`, `no`
  - `Bact_cul`: Received bacterial culture.
    - Possible values: `yes`, `no`
  - `Service`: Service.
    - Possible values: `med`, `surg`

# infantbp

Researchers investigated the link between high blood pressure and sodium intake by measuring infants' responses to salt and sugar solutions. They measured the vigor of infants' sucking (mean sucks per burst, MSB) when exposed to different solutions: water, 0.1 molar salt, 0.3 molar salt, and sugar. The responses were recorded over a series of periods using different stimuli: (i) nonnutritive sucking (ii) water, (iii) 5% sucrose + water, (iv) 15% sucrose + water, and (v) nonnutritive sucking.

- [infantbp.csv](./data/infantbp.csv)
  - `ID`:ID
  -Salt Taste Variables
    - `Mn_sbp`: Mean SBP
    - `Mn_dbp`: Mean DBP
    - `MSB1slt`: MSB-trial 1 water
    - `MSB2slt`: MSB-trial 2 water
    - `MSB3slt`: MSB-trial 3 0.1 molar salt + water
    - `MSB4slt`: MSB-trial 4 0.1 molar salt + water
    - `MSB5slt`: MSB-trial 5 water
    - `MSB6slt`: MSB-trial 6 water
    - `MSB7slt`: MSB-trial 7 0.3 molar salt + water
    - `MSB8slt`: MSB-trial 8 0.3 molar salt + water
    - `MSB9slt`: MSB-trial 9 water
    - `MSB10slt`: MSB-trial 10 water
  - Sugar Taste Variables
    - `MSB1sug`: MSB-trial 1 non-nutritive sucking
    - `MSB2sug`: MSB-trial 2 water
    - `MSB3sug`: MSB-trial 3 5% sucrose + water
    - `MSB4sug`: MSB-trial 4 15% sucrose + water
    - `MSB5sug`: MSB-trial 5 non-nutritive sucking
  - For MSB, 0 indicates the baby did not suck.

# lead

A study examined the psychological and neurological effects of lead exposure on children near a lead smelter in El Paso, Texas. Blood lead levels were measured, categorizing 46 children with levels ≥ 40 μg/mL as the exposed group. Another 78 children with levels < 40 μg/mL functioned as the control group. Key outcomes included finger–wrist taps (neurological function) and Wechsler full-scale IQ scores.

Other behavioral effects of lead include hyperactivity. In this study, parents also rated their children’s hyperactivity on a scale from 0 (normal) to 3 (very hyperactive). Hyperactivity measures are available for 49 control children and 35 exposed children.

- [lead.csv](./data/lead.csv)
  - Patient information
    - `id`: Identification number
    - `ageyrs`: Age in years
    - `sex`: Sex.
      - Possible values: `male`, `female`
  - Lead data
    - `area`: Distance of esidence from smelter on august 1972. Possible values:
      - `0-1` Miles from smelter
      - `1-2.5` Miles
      - `2.5-4.1` Miles
    - `lead_grp`: Blood lead level group. possible values:
      - `control` = Blood lead levels below 40 micrograms/100ml in both 1972 & 1973 (control group),
      - `current exposed` = Blood lead levels greater than or equal to 40 micrograms/100ml in both 72 & 73 or a level greater than or equal to 40 in 73 alone (3 cases only) (currently exposed group),
      - `previous exposed` = Blood lead levels greater than or equal to 40 micrograms/100ml in 72 and less than 40 in 73 (previously exposed group)
    - `Group`: group.
      - Possible values: `control`, `exposed`
    - `ld72`: Blood lead values (micrograms/100ml) in 72
    - `ld73`: Blood lead values (micrograms/100ml) in 73
    - `fst2yrs`: Did child live for 1st 2 years within 1 mile of smelter.
      - Possible values: `yes`, `no`.
    - `totyrs`: Total number of years spent within 4.1 miles of smelter
  - IQ Test Results
    - `iqv_inf`: INF - information subtest in WISC and WPPSI
    - `iqv_comp`: COMP - comprehension subtest in WISC and WPPSI
    - `iqv_ar`: AR - arithmetic subtest in WISC and WPPSI
    - `iqv_ds`: DS - digit span subtest(WISC) and sentence completion(WPPSI)
    - `iqv_raw`: V/RAW - raw score/verbal IQ
    - `iqp_pc`: PC - picture completion subtest in WISC and WPPSI
    - `iqp_bd`: BD - block design subtest in WISC and WPPSI
    - `iqp_oa`: OA - object assembly subtest(WISC), animal house subtest(WPPSI)
    - `iqp_cod`: COD - coding subtest(WISC), geometric design subtest(WPPSI)
    - `iqp_raw`: P/RAW - raw score/performance IQ (total of scores PC, BD, OA, & COD)
    - `hh_index`: HH/INDEX - Hollingshead index of social status
    - `iqv`: IQV - verbal IQ
    - `iqp`: IQP - performance IQ
    - `iqf`: IQF - full scale IQ (not sum or average of IQV D IQP)
    - `iq_type`: Type of IQ test (WISC usually given to children $\geq$ 5 years and 1 month of age WPPSI usually given to children $\leq$ 5 years of age).
      - Possible values: `WISC`, `WPPSI`
  - Symptom data (as reported by parents)
    - `pica`: Pica.
      - Possible values: `yes`, `no`.
    - `colic`: Colic.
      - Possible values: `yes`, `no`.
    - `clumsi`: Clumsiness.
      - Possible values: `yes`, `no`.
    - `irrit`: Irritability.
      - Possible values: `yes`, `no`.
    - `convul`: Convulsions.
      - Possible values: `yes`, `no`.
  - Neurological test data
    - `_2plat_r`: Number of taps for right hand in the 2-plate tapping test  (number of taps in one 10 second trial)
    - `_2plat_l`: Number OF taps for left hand in the 2-plate tapping test (number taps in one 10 second trial)
    - `visrea_r`: Visual reaction time right hand (milliseconds)
    - `visrea_l`: Visual reation time left hand (milliseconds)
    - `audrea_r`: Auditory reaction time right hand (milliseconds)
    - `audrea_l`: Auditory reaction time left hand (milliseconds)
    - `fwt_r`: Finger-wrist tapping test right hand (number of taps in one 10 second trial)
    - `fwt_l`: Finger-wrist tapping test left hand (#taps in one 10 second trial)
    - `hyperact`: WWPS - Werry-Weiss-Peters scale for hyperactivity
	  - `0` = no activity, $\ldots$, `4` = severly hyperactive (as reported by parents)
    - `maxfwt`: Finger-wrist tapping test in dominant hand (max of `fwt_r`,`fwt_l`)

# lvm

The Left Ventricular Mass Index (LVMI) measures the enlargement of the heart's left side, expressed in gm/ht(m)^2.7. High LVMI values can predict future cardiovascular disease in children. A study investigated the relationship between LVMI levels and blood pressure categories in children and adolescents aged 10-18. Blood pressure was categorized as Normal (`bpcat` = `normal`, bp percentile < 80%), Pre-Hypertensive (`bpcat` = `pre-hypertensive`, bp percentile ≥ 80% and < 90%), or Hypertensive (`bpcat` = `hypertensive`, bp percentile ≥ 90%)..

- [lvm.csv](./data/lvm.csv)
  - `ID`:	ID
  - `lvmht27`: Left ventricular mass – height corrected = Left Ventricular Mass/Height(m)$^{2.7}$, $g/m^{2.7}$
  - `bpcat`: Blood pressure category.
    - Possible values: `normal`, `pre-hypertensive`, `hypertensive`.
  - `gender`: Bender.
    - Possible values: `male`, `female`
  - `age`: in years
  - `BMI`: kg/m$^2$

# mice

Retinitis pigmentosa (RP) is a hereditary eye condition causing night blindness and visual field loss, typically between ages 10 and 40. Some patients become legally blind by 30, while others retain central vision past 60. A specific gene linked RP has been identified whose transmision is autosomal dominant. The disease progression is tracked using electroretinogram (ERG), measuring retinal electrical activity, which decreases as RP advances, affecting routine activities like driving and walking at night.

To test if sunlight exposure harms RP patients, researchers introduced the RP gene into mice, creating "RP mice." These mice were divided into light, dim, and dark lighting conditions from birth. A control group of normal mice was also subjected to similar conditions. ERG amplitudes (BAMP and AAMP) were measured at 15, 20, and 35 days of life for RP mice, and only BAMP was measured for normal mice.

- [mice.csv](./data/mice.csv)
  - `Id`: ID
  - `Group`: GROUP.
    - Possible values: `RP`, `NORMAL`
  - `Trtgrp`: TREATMENT GROUP.
    - Possible values: `LIGHT`, `DIM`, `DARK`.
  - `Age`: AGE (days)
  - `B_amp`: B AMP
  - `A_amp`: A AMP

# nifed

A clinical trial tested the effectiveness of nifedipine in reducing chest pain in hospitalized angina patients. The study lasted 14 days unless patients were withdrawn, discharged, or died. Patients were randomly assigned to receive either nifedipine or propranolol, starting at a standard dosage. If pain persisted or recurred, the dosage was increased in pre-specified steps. Patients in both groups could also receive nitrates as needed to control pain. The primary goal was to compare pain relief between nifedipine and propranolol, with a secondary goal of examining their effects on heart rate and blood pressure.

- [nifed.csv](./data/nifed.csv)
  - `Id`: ID
  - `trtgrp`: Treatment group,
    - `N` = nifedipine
    - `P` = placebo
  - `bashrtrt`: Baseline heart rate immediately prior to randomization (beats/min)
  - `lv1hrtrt`: Level 1 heart rate, Highest heart rate and systolic blood pressure at baseline and each level of therapy respectively (beats/min)
  - `lv2hrtrt`: Level 2 heart rate (beats/min)
  - `lv3hrtrt`: Level 3 heart rate (beats/min)
  - `bassys`: Baseline systolic bp immediately prior to randomization (mm Hg)
  - `lv1sys`: Level 1 systolic bp (mm Hg)
  - `lv2sys`: Level 2 systolic bp (mm Hg)
  - `lv3sys`: Level 3 systolic bp (mm Hg)

Missing values indicate that either
(a) the patient withdrew from the study prior to entering this level of therapy
(b) the patient achieved pain relief prior to reaching this level or therapy,
(c) the patient encountered this level of therapy, but this particular piece of data was missing.

# piriform

A study evaluated the FAIR test (hip flexion, adduction, and internal rotation) for diagnosing piriformis syndrome (PS), which affects the piriformis muscle in the buttock, causing lumbar and sciatic pain. The test measures nerve-conduction velocity differences between an aggravating and a neutral posture, with higher scores indicating a greater likelihood of PS. Data from 142 participants without PS and 489 with PS (diagnosed clinically) are available. A FAIR test score of ≥ 1.86 ms is proposed to define a positive result. The FAIR test value, MAXCHG, is recorded in milliseconds.

- [piriform.csv](./data/piriform.csv)
  - `ID`: ID
  - `piriform`: Piriformis Syndrome.
    - Possible values: `Negative`, `Positive`
  - `sex`: Sex.
    - Possible values: `male`, `female`
  - `age`: Age
  - `maxchg`: Max change between tibia and peroneal

# sexrat

It is often assumed that the gender distribution of consecutive children is independent. To test this hypothesis, birth records from the first five children in 51,868 families were analyzed. These data contain the frequency of how many times a pattern of child sexes showed up. E.g., MM (only two males) showed up 4400 times.

- [sexrat.csv](./data/sexrat.csv)
  - `nm_chld`: Number of children. For families with 5+ children, the sex of the first 5 children are listed. The number of children is given as 5 for such families.
  - `sx_1`: Sex of 1st born
  - `sx_2`: Sex of 2nd born
  - `sx_3`: Sex of 3rd born
  - `sx_4`: sex of 4th born
  - `sx_5`: sex of 5th born
  - `sexchldn`: Sex of all children. The sex of successive births is given. Thus, MMMF means that the first three children were males and the fourth child was a female. There were 484 such families.
  - `num_fam`: Number of families. Number of families with specific gender contribution of children

# smoke

A study was conducted among 234 individuals who wanted to quit smoking but had not yet done so. On the day they quit, their carbon monoxide (CO) levels were measured, and the time since their last cigarette was recorded. This CO level serves as an indicator of the number of cigarettes smoked daily before quitting but is influenced by the time since the last cigarette. Therefore, a "corrected CO level" was provided, adjusted for this time. Participant age, sex, and self-reported daily cigarette consumption were also recorded. The participants were followed for a year to determine the number of days they remained abstinent, ranging from 0 to 365 days.

- [smoke.csv](./data/smoke.csv)
  - `ID`: ID number
  - `Age`: age
  - `Gender`: Gender.
    - Possible values: `male`, `female`
  - `Cig_day`: Cigarettes/day
  - `CO`: Carbon monoxide (CO) (X 10)
  - `Min_last`: Minutes elapsed since last cigarette
  - `LogCOadj`: Log CO Adj * (X 1000). This variable represents adjusted carbon monoxide (CO) values. CO values were adjusted for minutes elapsed since last cigarette smoked using the formula Log 10 CO (Adjusted) = Log 10 CO - (-0.000638) X (Min - 80), where Min is the number of minutes elapsed since the last cigarette smoked.
  - `Day_abs`: Days abstinent  Those abstinent less than 1 day were given a value of zero.

# swiss

The Swiss Analgesic Study aimed to evaluate the impact of phenacetin-containing analgesics on kidney function and health. It involved 624 women from Basel, Switzerland, who had high phenacetin intake (study group) and 626 women with low or no phenacetin intake (control group). The study used urine N-acetyl-P-aminophenyl (NAPAP) levels to measure recent phenacetin use, dividing the study group into high-NAPAP and low-NAPAP subgroups. Both subgroups had higher NAPAP levels than the control group. The women were examined in 1967-1968 and again in 1969, 1970, 1971, 1972, 1975, and 1978, with kidney function assessed through various laboratory tests, including serum-creatinine levels.

- [swiss.csv](./data/swiss.csv)
  - `ID`: ID
  - `age`: age (yrs)
  - `group`: Group.
    - Possible values: `High NAPAP`, `Low NAPAP`, `control`
  - `creat_68`: Serum Creatinine 1968 (mg/dL)
  - `creat_69`: Serum Creatinine 1969 (mg/dL)
  - `creat_70`: Serum Creatinine 1970 (mg/dL)
  - `creat_71`: Serum Creatinine 1971 (mg/dL)
  - `creat_72`: Serum Creatinine 1972 (mg/dL)
  - `creat_75`: Serum Creatinine 1975 (mg/dL)
  - `creat_78`: Serum Creatinine 1978 (mg/dL)

# tear

A pilot study was conducted to evaluate an eye drop's effectiveness in preventing dry eye, measured by tear breakup time (TBUT). Fourteen participants tested three protocols:

- Protocol A: No blinking for 3 seconds before placebo instillation.
- Protocol B: No blinking for 6 seconds before placebo instillation (standard protocol).
- Protocol C: No blinking for 10 seconds before placebo instillation.

TBUT was recorded at baseline, immediately after, and at 5, 10, and 15 minutes post-instillation in a low-humidity environment. Each protocol was tested on the same participants, measuring both eyes with two replicates.

- [tear.csv](./data/tear.csv)
  - `ID`: ID
  - `od3bas1`: OD 3sec baseline 1
  - `od3bas2`: OD 3 sec baseline 2
  - `od3im1`: OD 3 sec immediately post 1
  - `od3im2`: OD 3 sec immediately post 2
  - `od3pst51`: OD 3 sec 5min post 1
  - `od3pst52`: OD 3 sec 5min post 2
  - `od3pt101`: OD 3 sec 10min post 1
  - `od3pt102`: OD 3 sec 10min post 2
  - `od3pt151`: OD 3 sec 15min post 1
  - `od3pt152`: OD 3 sec 15min post 2
  - `os3bas1`: OS 3sec baseline 1
  - `os3bas2`: OS 3 sec baseline 2
  - `os3im1`: OS 3 sec immediately post 1
  - `os3im2`: OS 3 sec immediately post 2
  - `os3pst51`: OS 3 sec 5min post 1
  - `os3pst52`: OS 3 sec 5min post 2
  - `os3pt101`: OS 3 sec 10min post 1
  - `os3pt102`: OS 3 sec 10min post 2
  - `os3pt151`: OS 3 sec 15min post 1
  - `os3pt152`: OS 3 sec 15min post 2
  - `od6bas1`: OD 6 sec baseline 1
  - `od6bas2`: OD 6 sec baseline 2
  - `od6im1`: OD 6 sec immediately post 1
  - `od6im2`: OD 6 sec immediately post 2
  - `od6pst51`: OD 6 sec 5min post 1
  - `od6pst52`: OD 6 sec 5min post 2
  - `od6pt101`: OD 6 sec 10min post 1
  - `od6pt102`: OD 6 sec 10min post 2
  - `od6pt151`: OD 6 sec 15min post 1
  - `od6pt152`: OD 6 sec 15min post 2
  - `os6bas1`: OS 6 sec baseline 1
  - `os6bas2`: OS 6 sec baseline 2
  - `os6im1`: OS 6 sec immediately post 1
  - `os6im2`: OS 6 sec immediately post 2
  - `os6pst51`: OS 6 sec 5min post 1
  - `os6pst52`: OS 6 sec 5min post 2
  - `os6pt101`: OS 6 sec 10min post 1
  - `os6pt102`: OS 6 sec 10min post 2
  - `os6pt151`: OS 6 sec 15min post 1
  - `os6pt152`: OS 6 sec 15min post 2
  - `od10bas1`: OD 10 sec baseline 1
  - `od10bas2`: OD 10 sec baseline 2
  - `od10im1`: OD 10 sec immediately post 1
  - `od10im2`: OD 10 sec immediately post 2
  - `od10ps51`: OD 10 sec 5min post 1
  - `od10ps52`: OD 10 sec 5min post 2
  - `od10p101`: OD 10 sec 10min post 1
  - `od10p102`: OD 10 sec 10min post 2
  - `od10p151`: OD 10 sec 15min post 1
  - `od10p152`: OD 10 sec 15min post 2
  - `os10bas1`: OS 10 sec baseline 1
  - `os10bas2`: OS 10 sec baseline 2
  - `os10im1`: OS 10 sec immediately post 1
  - `os10im2`: OS 10 sec immediately post 2
  - `os10ps51`: OS 10 sec 5min post 1
  - `os10ps52`: OS 10 sec 5min post 2
  - `os10p101`: OS 10 sec 10min post 1
  - `os10p102`: OS 10 sec 10min post 2
  - `os10p151`: OS 10 sec 15min post 1
  - `os10p152`: OS 10 sec 15min post 2


# temperat

A student records temperatures at 20 sites within her house for 30 days each. She records the outside temperature and the weather condition.

- [temperat.csv](./data/temperat.csv)
  - `Date`: Date (MDY)
  - `Out_temp`: Outside temerature (Degrees Fahrenheit)
  - `Room`: Room location
  - `In_temp`: Inside temperature (Degrees Fahrenheit)
  - `Cor_fac`: Correction factor added.
    - Possible values: `yes`, `no`
  - `Typ_wea`: Type of weather.
    - Possible values: `SUNNY`, `PARTLY CLOUDY`, `CLOUDY`, `RAINY`, `FOGGY`

# tennis1

A survey of tennis club members in the Boston area examined the occurrence of tennis elbow. Subjects reported anywhere from 0 to 8 episodes of tennis elbow. They were also asked about demographic factors and racquet characteristics.

- [tennis1.csv](./data/tennis1.csv)
  - `Id`: ID
  - `Age`: Age
  - `Sex`: Sex.
    - Possible values: `male`, `female`
  - `Num_epis`: Number of episodes of tennis elbow
  - `Typ_last`: Type of racquet used during last episode.
    - Possible values: `CONVENTIONAL SIZE`, `MID-SIZE`, `OVER-SIZE`
  - `Wgt_last`: Weight of racquet used during last episode.
    - Possible values: `HEAVY`, `MEDIUM`, `LIGHT`, `DO NOT KNOW`
  - `Mat_last`: Material of racquet used during last episode.
    - Possible values: `WOOD`, `ALUMINUM`, `FIBERGLASS AND COMPOSITE`, `GRAPHITE`, `STEEL`, `COMPOSITE`, `OTHER`
  - `Str_last`: String type of racquet used during last episode.
    - Possible values: `NYLON`, `GUT`, `DON'T KNOW`
  - `Typ_curr`: Type of racquet used currently.
    - Possible values: `CONVENTIONAL SIZE`, `MID-SIZE`, `OVER-SIZE`
  - `Wgt_curr`: Weight of racquet used currently.
    - Possible values: `HEAVY`, `MEDIUM`, `LIGHT`, `DO NOT KNOW`
  - `Mat_curr`: Material of racquet used currently.
    - Possible values: `WOOD`, `ALUMINUM`, `FIBERGLASS AND COMPOSITE`, `GRAPHITE`, `STEEL`, `COMPOSITE`, `OTHER`
  - `Str_curr`: String type of racquet used currently.
    - Possible values: `NYLON`, `GUT`, `DON'T KNOW`

# tennis2

Tennis elbow is a painful condition common among tennis players. Treatments include rest, heat, and anti-inflammatory medications like Motrin (ibuprofen). A clinical trial with 87 participants compared the effectiveness of Motrin vs. placebo. Participants were randomly divided into two groups: Group A received Motrin for 3 weeks, followed by a 2-week washout period, and then placebo for 3 weeks; Group B received the treatments in reverse order. Pain levels were measured on a 1-6 scale (1 = worse, 6 = completely improved) at the end of each treatment and washout period. The comparison was made (i) during  maximum  activity, (ii) 12  hours following maximum activity, (iii) during the average day, and  (iv) by overall impression of drug efficacy.

- [tennis2.csv](./data/tennis2.csv)
  - `id`: ID
  - `age`: Age
  - `sex`: Sex.
    - Possible values: `male`, `female`
  - `drg_ord`: Drug order.
    - Possible values: `MOTRIN-PLACEBO`, `PLACEBO-MOTRIN`
  - Period 2 = Pain scores after the first active drug period compared with baseline
    - `painmx_2`: During study period, pain during maximum activity vs baesline
      - `1` = Worse
      - `2` = Unchanged
      - `3` = Slightly improved (25%)
      - `4` = Moderately improved (50%)
      - `5` = Mostly improved (75%)
      - `6` = Completely improved
    - `pain12_2`: Within 12 hours following maximal activity, compared to same period at baseline  (same code as `painmx_2`)
    - `painav_2`: During the average day of study period pain vs. baseline (same code as `painmx_2`)
    - `painov_2`: Overall impression of drug efficacy vs. baseline (same code as `painmx_2`)
  - Period 3 = Pain scores after the washout period compared with baseline
    - `painmx_3`: During study period, pain during maximum activity vs baseline (same code as `painmx_2`)
    - `pain12_3`: Within 12 hours following maximal activity, compared to same period at baseline (same code as `painmx_2`)
    - `painav_3`: During the average day of study period pain vs baseline (same code as `painmx_2`)
    - `painov_3`: Overall impression of drug efficacy vs baseline (same code as `painmx_2`)
  - Period 4 = Pain scores after the second active drug period compared with baseline
    - `painmx_4`: During study period, pain during maximum activity vs baseline (same code as `painmx_2`)
    - `pain12_4`: Within 12 hours following maximal activity, compared to same period at baseline (same code as `painmx_2`)
    - `painav_4`: During the average day of study period pain vs baseline (same code as `painmx_2`)
    - `painov_4`: Overall impression of drug efficacy vs baseline (same code as `painmx_2`)

# valid

The food-frequency questionnaire (FFQ) is a common tool in dietary epidemiology to assess food consumption. It asks individuals to report their typical daily servings of over 100 food items from the past year, and a food-composition table calculates nutrient intakes. While FFQs are inexpensive, they are less accurate than diet records (DR), where participants document their weekly food intake, and a nutritionist calculates nutrient intakes. In a validation study, 173 nurses from the Nurses' Health Study completed 4 weeks of diet records and an FFQ. Data for saturated fat, total fat, alcohol consumption, and caloric intake from both methods recorded here.

- [valid.csv](./data/valid.csv)
  - `Id`: ID number
  - `sfat_dr`: Saturated fat-DR
  - `sfat_ffq`: Saturated fat-FFQ
  - `tfat_dr`: Total fat-DR
  - `tfat_ffq`: Total fat-FFQ
  - `alco_dr`: Alcohol consumption-DR
  - `alco_ffq`: Alcohol consumption-FFQ
  - `cal_dr`: Total calories-DR
  - `cal_ffq`: Total calories-FFQ

# wales

A study in South Wales investigated the hereditary factors of blood pressure in 623 individuals (propositii) over age 5 from two populations. The participants and their first-degree relatives had their blood pressure measured at home by one observer, with a baseline and three follow-up exams from the mid-1950s to the early 1960s. The dataset WALES.DAT includes familial blood pressure data from the Rhondda Fach and Vale of Glamorgan communities.

- [wales.csv](./data/wales.csv)
  - `ID`: ID
  - `record`:
  - `sex`:
  - `area`:
  - `propositus`:
  - `sexofprop`:
  - `relationship`:
  - `doubler`:
  - `surveystat`:
  - `maritalstt`:
  - `age`:
  - `parity`:
  - `height`:
  - `weight`:
  - `armgrth`:
  - `triceps`:
  - `sysbp`:
  - `diasbp`:
  - `pulse`:
  - `albumin`:
  - `glucose`:
  - `bacteria`:
  - `occupation`:
  - `hypertension`:
  - `diabetes`:
  - `pregnancy`:
  - `pet_fibroids`:
  - `angina`:
  - `pmi`:
  - `inter_claud`:

# References
