---
title: "t-distribution"
author: "David Gerard"
date: today
format: html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
            fig.width = 4, 
            fig.height = 3, 
            fig.align = "center")
ggplot2::theme_set(ggplot2::theme_bw() + ggplot2::theme(strip.background = ggplot2::element_rect(fill = "white")))
```

## Learning Objectives

- Work with $t$-distribution
- Understand $t$-distribution

# $t$-distribution

- $t$ vs Normal(0, 1)

  ```{r, echo = FALSE, message=FALSE, warning=FALSE}
  library(tidyverse)
  library(ggthemes)
  x <- seq(-4, 4, length = 200)
  data.frame(df = as.factor(c(rep(1, length(x)), rep(5, length(x)), rep(Inf, length(x)))),
             x = c(x, x, x),
             y = c(dt(x = x, df = 1),
                   dt(x = x, df = 5),
                   dt(x = x, df = Inf))) ->
    dfdat
  ggplot(dfdat, mapping = aes(x = x, y = y, color = df, lty = df)) +
    geom_line() +
    scale_color_colorblind() +
    ylab("f(x)")
  ```

- A lot more extreme values in a t

  ```{r, echo = FALSE}
  set.seed(1)
  tibble(samp = rnorm(1000)) |>
    ggplot(aes(x = samp)) +
    geom_histogram(bins = 30, fill = "white", color = "black") +
    ggtitle("Normal") +
    xlab("Sample Values")
  ```

  ```{r, echo = FALSE}
  set.seed(1)
  tibble(samp = rt(1000, df = 2)) |>
    ggplot(aes(x = samp)) +
    geom_histogram(bins = 30, fill = "white", color = "black") +
    ggtitle("t with 2 df") +
    xlab("Sample Values")
  ```

# Working with $t$ Distribution in R:

- Density Function

  ```{r}
  dt(x = -6, df = 2)
  ```
  
  ```{r, echo = FALSE}
  library(ggplot2)
  x <- seq(-6, 6, length = 100)
  y <- dt(x, df = 1)
  qplot(x, y, geom = "line", ylab = "f(x)") +
    geom_segment(dat = data.frame(x = 2, xend = 2, y = 0, yend = dt(x = 2, df = 2)), aes(x = x, y = y, xend = xend, yend = yend), lty = 2, col = 2)
  ```

- Random Generation

  ```{r}
  samp <- rt(n = 1000, df = 2)
  head(samp)
  ```
  
  ```{r, echo = FALSE}
  qplot(samp, geom = "histogram", fill = I("white"), color = I("black"), bins = 20)
  ```


- Cumulative Distribution Function

  ```{r}
  pt(q = 2, df = 2)
  ```
  
  ```{r, echo = FALSE}
  x <- seq(-6, 6, length = 500)
  y <- dt(x,  df = 2)
  polydf <- data.frame(x = c(min(x), x[x < 2], 2, 0), 
                       y = c(0, y[x < 2], 0, 0))
  qplot(x, y, geom = "line", ylab = "f(x)") +
    geom_polygon(data = polydf, mapping = aes(x = x, y = y), 
                 fill = "red", alpha = 3/4)
  ```

- Quantile Function: Rosner denotes the following $t_{2,0.9082}$

  ```{r}
  qt(p = 0.9082, df = 2)
  ```
  
  ```{r, echo = FALSE}
  x <- seq(-6, 6, length = 500)
  y <- dt(x, df = 2)
  polydf <- data.frame(x = c(min(x), x[x < 2], 2, 0), 
                       y = c(0, y[x < 2], 0, 0))
  qplot(x, y, geom = "line", ylab = "f(x)") +
    geom_polygon(data = polydf, mapping = aes(x = x, y = y), 
                 fill = "red", alpha = 3/4) +
    annotate(geom = "text", x = 0, y = 0.1, label = "0.9082", color = "white")
  ```
  
- **Exercise**: In the Rosner notation, what does $t_{20, 0.95}$ mean? Calculate it.

```{r}
#| echo: false
#| eval: false
# 0.95 quantile of a t-distribution with 20 degrees of freedom
qt(p = 0.95, df = 20)
```

